@startuml uikulku
käyttäjä--> (pääsivu)
järjestelmävalvoja --> (pääsivu)
    (pääsivu) --> (Kirjaudu sisään)
    (Kirjaudu sisään)--> (Luo uusi normaali käyttäjä)
    (Luo uusi normaali käyttäjä)--> (Kirjaudu sisään)
    (Kirjaudu sisään)--> (Luo uusi järjestelmävalvoja)
    (Luo uusi järjestelmävalvoja)--> (Kirjaudu sisään)
    (Kirjaudu sisään)--> (pääsivu kirjautuneena)
    (pääsivu kirjautuneena)-->(profiili)
    (profiili)--> (pääsivu kirjautuneena)
    (pääsivu kirjautuneena)--> (1 lisää uusi postaus)
    
    (kirjaudu ulos)-->(pääsivu)
    (pääsivu kirjautuneena)--> (kirjaudu ulos)
    (profiili)--> (kirjaudu ulos)
    (1 lisää uusi postaus)-->(2 lähetä kuva)
    (1 lisää uusi postaus)-->(peruuta)
    (2 lähetä kuva)-->(1 lisää uusi postaus)
    (2 lähetä kuva)--> (peruuta)
    (2 lähetä kuva)-->(3 lisää kuvaus)
    (3 lisää kuvaus)--> (peruuta)
    (3 lisää kuvaus)-->(2 lähetä kuva)
    (3 lisää kuvaus)--> (4 lisää tagit)
    (4 lisää tagit)--> (peruuta)
    (4 lisää tagit)--> (5 lisää aika)
    (4 lisää tagit)--> (3 lisää kuvaus)
    (5 lisää aika)--> (peruuta)
    (5 lisää aika)--> (6 lisää kategoria)
    (5 lisää aika)--> (4 lisää tagit)
    (6 lisää kategoria)--> (7 lisää tagit)
    (6 lisää kategoria)-->(5 lisää aika)
    (6 lisää kategoria)--> (peruuta)
    (7 lisää tagit)--> (8 lisää linkki)
    (7 lisää tagit)--> (peruuta)
    (8 lisää linkki)-->(7 lisää tagit)
    (8 lisää linkki)-->(peruuta)
    (8 lisää linkki)--> (9 lisää kommentti)
    (9 lisää kommentti)-->(8 lisää linkki)
    (9 lisää kommentti)-->(peruuta)
    (9 lisää kommentti)--> (profiili)
    (peruuta)--> (profiili)
    
    
    
    
    
    
    (Kirjaudu sisään)-->(järjestelmävalvoja ikkuna)
    (järjestelmävalvoja ikkuna)--> (statistiikka)
    (statistiikka)--> (järjestelmävalvoja ikkuna)
  @enduml